[package]
cairo-version = "2.12.2"
name = "jokers_of_neon_classic"
version = "0.19.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[dependencies]
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
jokers_of_neon_lib = { git = "https://github.com/caravana-studio/jokers-of-neon-lib", branch="develop" }
starknet = "2.12.2"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "jokers_of_neon_lib::random::m_Salt",
]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.0"

[profile.slot]
