[package]
cairo-version = "2.13.1"
name = "jokers_of_neon_mods"
version = "0.20.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[dependencies]
dojo = "1.8.0"
dojo_cairo_macros = "1.8.0"
jokers_of_neon_lib = { git = "https://github.com/caravana-studio/jokers-of-neon-lib", branch = "special-cards-season-4" }
starknet = "2.13.1"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.13.1"
dojo_cairo_test = "1.8.0"

[profile.aws-testnet]
[profile.aws-mainnet]

[lib]
