pub const RAGE_CARD_SILENT_HEARTS: u32 = 20001;
pub const RAGE_CARD_SILENT_CLUBS: u32 = 20002;
pub const RAGE_CARD_SILENT_DIAMONDS: u32 = 20003;
pub const RAGE_CARD_SILENT_SPADES: u32 = 20004;
pub const RAGE_CARD_SILENT_JOKERS: u32 = 20005;

pub const RAGE_CARD_ZERO_WASTE: u32 = 20007;
pub const RAGE_CARD_HAND_LEECH: u32 = 20016;

pub const RAGE_CARD_DIMINISHED_HOLD: u32 = 20006;
pub const RAGE_CARD_STRATEGIC_QUARTED: u32 = 20009;

pub const RAGE_CARD_SILENT_FIGURES: u32 = 20012;
pub const RAGE_CARD_SILENT_ACES: u32 = 20013;

pub const RAGE_CARD_DOUBLE_TROUBLE: u32 = 20020;
pub const RAGE_CARD_BETRAYING_THE_WEAK: u32 = 20021;

pub const RAGE_CARD_LOCKED_PLAYS: u32 = 20022;
pub const RAGE_CARD_PUNCHED_TICKET: u32 = 20023;
pub const RAGE_CARD_DEBUFF_FLUSH: u32 = 20024;
pub const RAGE_CARD_FAVORITE_LOCK: u32 = 20025;

pub fn rages_ids_all() -> Array<u32> {
    array![
        RAGE_CARD_SILENT_HEARTS, RAGE_CARD_SILENT_CLUBS, RAGE_CARD_SILENT_DIAMONDS, RAGE_CARD_SILENT_SPADES,
        RAGE_CARD_SILENT_JOKERS, RAGE_CARD_ZERO_WASTE, RAGE_CARD_HAND_LEECH, RAGE_CARD_DIMINISHED_HOLD,
        RAGE_CARD_STRATEGIC_QUARTED, RAGE_CARD_SILENT_FIGURES, RAGE_CARD_BETRAYING_THE_WEAK, RAGE_CARD_DOUBLE_TROUBLE,
        RAGE_CARD_PUNCHED_TICKET, RAGE_CARD_LOCKED_PLAYS,
    ]
}

pub fn rages_info() -> (Span<Span<u32>>, Span<u32>, Span<u32>, Span<u32>) {
    // C-Grade Group
    let C_RAGES_PROBABILITY = 45;
    let C_RAGES = array![
        RAGE_CARD_SILENT_HEARTS, RAGE_CARD_SILENT_CLUBS, RAGE_CARD_SILENT_DIAMONDS, RAGE_CARD_SILENT_SPADES,
        RAGE_CARD_SILENT_FIGURES, RAGE_CARD_BETRAYING_THE_WEAK,
    ]
        .span();
    let C_RAGES_REWARDS = 500;
    let C_RAGES_LEVEL = 1;

    // B-Grade Group
    let B_RAGES_PROBABILITY = 25;
    let B_RAGES = array![
        RAGE_CARD_SILENT_JOKERS, RAGE_CARD_HAND_LEECH, RAGE_CARD_DOUBLE_TROUBLE, RAGE_CARD_LOCKED_PLAYS,
    ]
        .span();
    let B_RAGES_REWARDS = 750;
    let B_RAGES_LEVEL = 2;

    // A-Grade Group
    let A_RAGES_PROBABILITY = 20;
    let A_RAGES = array![RAGE_CARD_DIMINISHED_HOLD].span();
    let A_RAGES_REWARDS = 1000;
    let A_RAGES_LEVEL = 3;

    // S-Grade Group
    let S_RAGES_PROBABILITY = 10;
    let S_RAGES = array![RAGE_CARD_ZERO_WASTE, RAGE_CARD_STRATEGIC_QUARTED, RAGE_CARD_PUNCHED_TICKET].span();
    let S_RAGES_REWARDS = 1500;
    let S_RAGES_LEVEL = 4;

    assert(
        C_RAGES_PROBABILITY + B_RAGES_PROBABILITY + A_RAGES_PROBABILITY + S_RAGES_PROBABILITY == 100,
        'wrong probability sum',
    );
    (
        array![C_RAGES, B_RAGES, A_RAGES, S_RAGES].span(),
        array![C_RAGES_PROBABILITY, B_RAGES_PROBABILITY, A_RAGES_PROBABILITY, S_RAGES_PROBABILITY].span(),
        array![C_RAGES_REWARDS, B_RAGES_REWARDS, A_RAGES_REWARDS, S_RAGES_REWARDS].span(),
        array![C_RAGES_LEVEL, B_RAGES_LEVEL, A_RAGES_LEVEL, S_RAGES_LEVEL].span(),
    )
}
