const RAGE_CARD_SILENT_HEARTS: u32 = 401;
const RAGE_CARD_SILENT_CLUBS: u32 = 402;
const RAGE_CARD_SILENT_DIAMONDS: u32 = 403;
const RAGE_CARD_SILENT_SPADES: u32 = 404;
const RAGE_CARD_SILENT_JOKERS: u32 = 405;
const RAGE_CARD_SILENT_FIGURES: u32 = 412;

const RAGE_CARD_ZERO_WASTE: u32 = 407;
const RAGE_CARD_HAND_LEECH: u32 = 416;

const RAGE_CARD_DIMINISHED_HOLD: u32 = 406;
const RAGE_CARD_STRATEGIC_QUARTED: u32 = 409;
const RAGE_CARD_UNEXPECTED_SACRIFICE: u32 = 408; // Hard to implement with current scheme

fn rages_ids_all() -> Array<u32> {
    array![
        RAGE_CARD_SILENT_HEARTS, RAGE_CARD_SILENT_CLUBS, RAGE_CARD_SILENT_DIAMONDS, RAGE_CARD_SILENT_SPADES, RAGE_CARD_SILENT_JOKERS,
        RAGE_CARD_ZERO_WASTE, RAGE_CARD_HAND_LEECH, RAGE_CARD_DIMINISHED_HOLD, RAGE_CARD_STRATEGIC_QUARTED, RAGE_CARD_UNEXPECTED_SACRIFICE
    ]
}