const SPECIAL_MULTI_FOR_HEART_ID: u32 = 10000;
const SPECIAL_MULTI_FOR_CLUB_ID: u32 = 10001;
const SPECIAL_MULTI_FOR_DIAMOND_ID: u32 = 10002;
const SPECIAL_MULTI_FOR_SPADE_ID: u32 = 10003;
const SPECIAL_INCREASE_LEVEL_PAIR_ID: u32 = 10004;
const SPECIAL_INCREASE_LEVEL_DOUBLE_PAIR_ID: u32 = 10005;
const SPECIAL_INCREASE_LEVEL_STRAIGHT_ID: u32 = 10006;
const SPECIAL_INCREASE_LEVEL_FLUSH_ID: u32 = 10007;
const SPECIAL_JOKER_BOOSTER_ID: u32 = 10010;
const SPECIAL_POWER_UP_BOOSTER_ID: u32 = 10011;
const SPECIAL_POINTS_FOR_FIGURES_ID: u32 = 10012;
const SPECIAL_MULTI_ACES_ID: u32 = 10013;
const SPECIAL_ALL_CARDS_TO_HEARTS_ID: u32 = 10014;
const SPECIAL_HAND_THIEF_ID: u32 = 10015;
const SPECIAL_EXTRA_HELP_ID: u32 = 10016;
const SPECIAL_LUCKY_SEVEN_ID: u32 = 10017;
const SPECIAL_NEON_BONUS_ID: u32 = 10018;
const SPECIAL_INITIAL_ADVANTAGE_ID: u32 = 10020;
const SPECIAL_LUCKY_HAND_ID: u32 = 10021;
const SPECIAL_DISCARD_MASTERY_ID: u32 = 10022;
const SPECIAL_SECOND_CHANCE_ID: u32 = 10023;
const SPECIAL_NEON_SYNERGY_ID: u32 = 10025;
const SPECIAL_WANTED_JOKER_ID: u32 = 10036;
const SPECIAL_PLUS_DISCARDS_ID: u32 = 10037;
const SPECIAL_PLUS_PLAYS_ID: u32 = 10038;
const SPECIAL_INCREASE_LEVEL_FULL_HOUSE_ID: u32 = 10043;
const SPECIAL_INCREASE_LEVEL_THREE_OF_A_KIND_ID: u32 = 10044;
const SPECIAL_INCREASE_LEVEL_FOUR_OF_A_KIND_ID: u32 = 10045;
const SPECIAL_INCREASE_LEVEL_FIVE_OF_A_KIND_ID: u32 = 10046;
const SPECIAL_RANDOM_MULTI_FOR_HEART_ID: u32 = 10047;
const SPECIAL_RANDOM_MULTI_FOR_CLUB_ID: u32 = 10048;
const SPECIAL_RANDOM_MULTI_FOR_DIAMOND_ID: u32 = 10049;
const SPECIAL_RANDOM_MULTI_FOR_SPADE_ID: u32 = 10050;

fn specials_ids_all() -> Array<u32> {
    array![
        SPECIAL_MULTI_FOR_HEART_ID,
        SPECIAL_MULTI_FOR_CLUB_ID,
        SPECIAL_MULTI_FOR_DIAMOND_ID,
        SPECIAL_MULTI_FOR_SPADE_ID,
        SPECIAL_INCREASE_LEVEL_PAIR_ID,
        SPECIAL_INCREASE_LEVEL_DOUBLE_PAIR_ID,
        SPECIAL_INCREASE_LEVEL_STRAIGHT_ID,
        SPECIAL_INCREASE_LEVEL_FLUSH_ID,
        SPECIAL_JOKER_BOOSTER_ID,
        SPECIAL_POWER_UP_BOOSTER_ID,
        SPECIAL_POINTS_FOR_FIGURES_ID,
        SPECIAL_MULTI_ACES_ID,
        SPECIAL_ALL_CARDS_TO_HEARTS_ID,
        SPECIAL_HAND_THIEF_ID,
        SPECIAL_EXTRA_HELP_ID,
        SPECIAL_LUCKY_SEVEN_ID,
        SPECIAL_NEON_BONUS_ID,
        SPECIAL_INITIAL_ADVANTAGE_ID,
        SPECIAL_LUCKY_HAND_ID,
        SPECIAL_DISCARD_MASTERY_ID,
        SPECIAL_PLUS_DISCARDS_ID,
        SPECIAL_PLUS_PLAYS_ID,
        SPECIAL_INCREASE_LEVEL_FULL_HOUSE_ID,
        SPECIAL_INCREASE_LEVEL_THREE_OF_A_KIND_ID,
        SPECIAL_INCREASE_LEVEL_FOUR_OF_A_KIND_ID,
        SPECIAL_INCREASE_LEVEL_FIVE_OF_A_KIND_ID,
        SPECIAL_RANDOM_MULTI_FOR_HEART_ID,
        SPECIAL_RANDOM_MULTI_FOR_CLUB_ID,
        SPECIAL_RANDOM_MULTI_FOR_DIAMOND_ID,
        SPECIAL_RANDOM_MULTI_FOR_SPADE_ID,
        SPECIAL_WANTED_JOKER_ID,
        SPECIAL_SECOND_CHANCE_ID,
    ]
}

fn specials_shop_info() -> (Span<Span<u32>>, Span<u32>, Span<u32>) {
    // C-Grade Group
    let C_SPECIALS_PROBABILITY = 45;
    let C_SPECIALS_COST = 1000;
    let C_SPECIALS = array![
        SPECIAL_MULTI_FOR_HEART_ID,
        SPECIAL_MULTI_FOR_CLUB_ID,
        SPECIAL_MULTI_FOR_DIAMOND_ID,
        SPECIAL_MULTI_FOR_SPADE_ID,
        SPECIAL_INCREASE_LEVEL_PAIR_ID,
        SPECIAL_INCREASE_LEVEL_DOUBLE_PAIR_ID,
        SPECIAL_LUCKY_HAND_ID,
        SPECIAL_WANTED_JOKER_ID,
    ]
        .span();

    // B-Grade Group
    let B_SPECIALS_PROBABILITY = 25;
    let B_SPECIALS_COST = 1750;
    let B_SPECIALS = array![
        SPECIAL_INCREASE_LEVEL_STRAIGHT_ID,
        SPECIAL_INCREASE_LEVEL_FLUSH_ID,
        SPECIAL_MULTI_ACES_ID,
        SPECIAL_NEON_BONUS_ID,
        SPECIAL_INCREASE_LEVEL_THREE_OF_A_KIND_ID,
        SPECIAL_RANDOM_MULTI_FOR_HEART_ID,
        SPECIAL_RANDOM_MULTI_FOR_CLUB_ID,
        SPECIAL_RANDOM_MULTI_FOR_DIAMOND_ID,
        SPECIAL_RANDOM_MULTI_FOR_SPADE_ID,
    ]
        .span();

    // A-Grade Group
    let A_SPECIALS_PROBABILITY = 15;
    let A_SPECIALS_COST = 3500;
    let A_SPECIALS = array![
        SPECIAL_PLUS_PLAYS_ID,
        SPECIAL_PLUS_DISCARDS_ID,
        SPECIAL_INCREASE_LEVEL_FULL_HOUSE_ID,
        SPECIAL_INCREASE_LEVEL_FOUR_OF_A_KIND_ID,
        SPECIAL_INCREASE_LEVEL_FIVE_OF_A_KIND_ID,
        SPECIAL_HAND_THIEF_ID,
        SPECIAL_LUCKY_SEVEN_ID,
        SPECIAL_POINTS_FOR_FIGURES_ID,
        SPECIAL_ALL_CARDS_TO_HEARTS_ID,
        SPECIAL_DISCARD_MASTERY_ID,
    ]
        .span();

    // S-Grade Group
    let S_SPECIALS_PROBABILITY = 15;
    let S_SPECIALS_COST = 5000;
    let S_SPECIALS = array![
        SPECIAL_EXTRA_HELP_ID,
        SPECIAL_JOKER_BOOSTER_ID,
        SPECIAL_POWER_UP_BOOSTER_ID,
        SPECIAL_INITIAL_ADVANTAGE_ID,
        SPECIAL_SECOND_CHANCE_ID,
    ]
        .span();

    assert(
        C_SPECIALS_PROBABILITY + B_SPECIALS_PROBABILITY + A_SPECIALS_PROBABILITY + S_SPECIALS_PROBABILITY == 100,
        'wrong probability sum',
    );
    (
        array![C_SPECIALS, B_SPECIALS, A_SPECIALS, S_SPECIALS].span(),
        array![C_SPECIALS_PROBABILITY, B_SPECIALS_PROBABILITY, A_SPECIALS_PROBABILITY, S_SPECIALS_PROBABILITY].span(),
        array![C_SPECIALS_COST, B_SPECIALS_COST, A_SPECIALS_COST, S_SPECIALS_COST].span(),
    )
}
