name: JON

on:
    push:
        branches:
        - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    workflow_dispatch:

env:
  DOJO_VERSION: v1.1.2
  SCARB_VERSION: v2.9.2

jobs:
  check:
    runs-on: ubuntu-latest
    name: Format
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Format
        run: scarb fmt --check
        shell: bash

  build:
    runs-on: ubuntu-latest
    name: Build
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: sozo build
        shell: bash
